version: '3.8'

services:
  # Housing Price Prediction API
  housing-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: housing-price-api
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    volumes:
      - ./mlruns:/app/mlruns
      - ./logs:/app/logs
      - ./data:/app/data
    networks:
      - housing-network
    restart: unless-stopped

  # MLflow Tracking Server
  mlflow:
    image: python:3.9-slim
    container_name: mlflow-server
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/app/mlruns
      - ./mlflow.db:/app/mlflow.db
    working_dir: /app
    command: >
      bash -c "
        pip install mlflow==2.5.0 &&
        mlflow server 
        --host 0.0.0.0 
        --port 5000 
        --backend-store-uri sqlite:///mlflow.db
      "
    networks:
      - housing-network
    restart: unless-stopped

networks:
  housing-network:
    driver: bridge