# Parameters for DVC pipeline

# Data parameters
data:
  raw_data_path: "data/raw/"
  processed_data_path: "data/processed/"
  test_size: 0.2
  validation_size: 0.2
  random_state: 42

# Model training parameters
train:
  # Cross-validation
  cv_folds: 5
  scoring_metric: "neg_mean_squared_error"
  
  # Linear Regression
  linear_regression:
    fit_intercept: [true, false]
    
  # Ridge Regression  
  ridge_regression:
    alpha: [0.1, 1.0, 10.0, 100.0, 1000.0]
    
  # Random Forest
  random_forest:
    n_estimators: [50, 100, 200]
    max_depth: [10, 20, 30, null]
    min_samples_split: [2, 5, 10]
    min_samples_leaf: [1, 2, 4]
    random_state: 42
    
  # Decision Tree
  decision_tree:
    max_depth: [5, 10, 15, 20, null]
    min_samples_split: [2, 5, 10, 20]
    min_samples_leaf: [1, 2, 5, 10]
    random_state: 42

# MLflow parameters
mlflow:
  tracking_uri: "file:./mlruns"
  experiment_name: "housing-price-prediction"
  registered_model_name: "HousingPriceModel"

# Evaluation parameters
evaluate:
  metrics:
    - "rmse"
    - "mae" 
    - "r2"
  plots:
    - "residuals"
    - "feature_importance"
    - "prediction_vs_actual"

# API parameters
api:
  host: "0.0.0.0"
  port: 8000
  model_stage: "Production"