# Alertmanager configuration for Housing Price Prediction MLOps Pipeline
global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@housing-mlops.local'
  smtp_auth_username: 'alerts@housing-mlops.local'
  smtp_auth_password: 'password'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
    - match:
        severity: warning
      receiver: 'warning-alerts'

receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://housing-api:8000/monitoring/alerts/webhook'
        send_resolved: true

  - name: 'critical-alerts'
    email_configs:
      - to: 'admin@housing-mlops.local'
        subject: 'CRITICAL: {{ .GroupLabels.alertname }}'
        body: |
          Alert: {{ .GroupLabels.alertname }}
          Severity: {{ .CommonLabels.severity }}
          
          {{ range .Alerts }}
          Description: {{ .Annotations.description }}
          Summary: {{ .Annotations.summary }}
          Started: {{ .StartsAt }}
          {{ end }}
    webhook_configs:
      - url: 'http://housing-api:8000/monitoring/alerts/webhook'
        send_resolved: true

  - name: 'warning-alerts'
    email_configs:
      - to: 'team@housing-mlops.local'
        subject: 'WARNING: {{ .GroupLabels.alertname }}'
        body: |
          Alert: {{ .GroupLabels.alertname }}
          Severity: {{ .CommonLabels.severity }}
          
          {{ range .Alerts }}
          Description: {{ .Annotations.description }}
          Summary: {{ .Annotations.summary }}
          Started: {{ .StartsAt }}
          {{ end }}
    webhook_configs:
      - url: 'http://housing-api:8000/monitoring/alerts/webhook'
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']