# Prometheus configuration for Housing Price Prediction MLOps Pipeline
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Housing Price Prediction API
  - job_name: 'housing-api'
    static_configs:
      - targets: ['localhost:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    
  # System metrics (if node_exporter is running)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
    scrape_interval: 15s
    
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s

  # MLflow tracking server (if running)
  - job_name: 'mlflow'
    static_configs:
      - targets: ['localhost:5000']
    scrape_interval: 30s
    metrics_path: '/metrics'
    scrape_timeout: 10s