name: Test Docker Push

on:
  workflow_dispatch:  # Manual trigger for testing

env:
  REGISTRY: docker.io
  IMAGE_NAME: housing-price-api

jobs:
  test-docker-push:
    runs-on: ubuntu-latest
    name: Test Docker Build and Push
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}
        tags: |
          type=raw,value=test-{{sha}}
          type=raw,value=test-latest
          
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        
    - name: Verify push success
      run: |
        echo "✅ Docker image pushed successfully!"
        echo "Tags: ${{ steps.meta.outputs.tags }}"
        echo "You can now pull with: docker pull ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:test-latest"